// Creature definitions and passive ability system

export const CREATURES = [
  {
    id: 'slime',
    name: 'Slime',
    icon: '🟢',
    rarity: 'common',
    ability: 'Every 5th bumper hit creates an extra ball.',
    description: 'A gooey creature that loves bouncing.',
    passive: 'extra_ball_on_bumper',
    passiveValue: 5,
  },
  {
    id: 'turtle',
    name: 'Turtle',
    icon: '🐢',
    rarity: 'common',
    ability: 'Balls slow down after each peg hit, increasing combo window.',
    description: 'Patience is power.',
    passive: 'slow_ball',
    passiveValue: 0.88,
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    icon: '🔥',
    rarity: 'rare',
    ability: 'A ball that lands in a losing slot has 35% chance to be relaunched.',
    description: 'Death is just a detour.',
    passive: 'relaunch_on_loss',
    passiveValue: 0.35,
  },
  {
    id: 'mushroom',
    name: 'Mushroom',
    icon: '🍄',
    rarity: 'uncommon',
    ability: 'Adds 3 bonus pegs to the board at the start of each run.',
    description: 'Spreads its spores throughout the machine.',
    passive: 'bonus_pegs',
    passiveValue: 3,
  },
  {
    id: 'ghost',
    name: 'Ghost',
    icon: '👻',
    rarity: 'rare',
    ability: 'Balls can occasionally pass through obstacles to reach hidden slots.',
    description: 'Exists between worlds.',
    passive: 'phase_through',
    passiveValue: 0.15,
  },
  {
    id: 'dragon',
    name: 'Dragon',
    icon: '🐉',
    rarity: 'epic',
    ability: 'Every 10th peg hit triggers a chain reaction hitting 3 nearby pegs.',
    description: 'Ancient power flows through each bounce.',
    passive: 'chain_reaction',
    passiveValue: 10,
  },
  {
    id: 'cat',
    name: 'Lucky Cat',
    icon: '🐱',
    rarity: 'uncommon',
    ability: 'All gold rewards are increased by 25%.',
    description: 'Fortune follows those it favors.',
    passive: 'gold_bonus',
    passiveValue: 0.25,
  },
  {
    id: 'owl',
    name: 'Wise Owl',
    icon: '🦉',
    rarity: 'uncommon',
    ability: 'Reveals which slots are multiplied before the ball is dropped.',
    description: 'Knowledge shapes destiny.',
    passive: 'reveal_slots',
    passiveValue: 1,
  },
  {
    id: 'crab',
    name: 'Crab',
    icon: '🦀',
    rarity: 'common',
    ability: 'Bumpers push balls sideways with extra force, improving spread.',
    description: 'Sideways is always an option.',
    passive: 'bumper_push',
    passiveValue: 1.4,
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    icon: '🦄',
    rarity: 'legendary',
    ability: 'One random slot per run becomes a JACKPOT slot (10× multiplier).',
    description: 'Only the truly fortunate ever glimpse one.',
    passive: 'jackpot_slot',
    passiveValue: 10,
  },
  {
    id: 'spider',
    name: 'Spider',
    icon: '🕷️',
    rarity: 'uncommon',
    ability: 'Adds webs to 2 pegs that trap balls briefly, boosting combo score.',
    description: 'Every trap is an opportunity.',
    passive: 'web_pegs',
    passiveValue: 2,
  },
  {
    id: 'wolf',
    name: 'Wolf',
    icon: '🐺',
    rarity: 'rare',
    ability: 'Ball speed increases after hitting 5 consecutive pegs.',
    description: 'The hunt accelerates.',
    passive: 'speed_streak',
    passiveValue: 5,
  },
  {
    id: 'octopus',
    name: 'Octopus',
    icon: '🐙',
    rarity: 'rare',
    ability: 'Spawns 2 extra bumpers that rotate positions each run.',
    description: 'Arms everywhere at once.',
    passive: 'rotating_bumpers',
    passiveValue: 2,
  },
  {
    id: 'bee',
    name: 'Queen Bee',
    icon: '🐝',
    rarity: 'epic',
    ability: 'Hitting a gold peg grants a bonus spin that drops an additional ball.',
    description: 'The hive rewards the diligent.',
    passive: 'gold_peg_bonus_ball',
    passiveValue: 1,
  },
  {
    id: 'crystal_fox',
    name: 'Crystal Fox',
    icon: '🦊',
    rarity: 'legendary',
    ability: 'Every 3rd run, the entire board is mirrored, opening new paths.',
    description: 'Sees through illusions to hidden paths.',
    passive: 'mirror_board',
    passiveValue: 3,
  },
];

/** Get a creature definition by id */
export function getCreature(id) {
  return CREATURES.find(c => c.id === id);
}

/** Get all creatures of a given rarity */
export function getByRarity(rarity) {
  return CREATURES.filter(c => c.rarity === rarity);
}
