// Permanent and temporary upgrade definitions

import { UPGRADE_TYPE } from './constants.js';

/** Temporary upgrades available during a run */
export const TEMP_UPGRADES = [
  {
    id: 'triple_bounce',
    name: 'Triple Bounce',
    icon: '🎯',
    type: 'passive',
    description: 'Every third peg hit deals triple score.',
    effect: 'triple_bounce_damage',
    value: 3,
  },
  {
    id: 'magnetic_ball',
    name: 'Magnetic Ball',
    icon: '🧲',
    type: 'passive',
    description: 'Ball gently steers toward bumpers.',
    effect: 'magnetic_to_bumpers',
    value: 0.15,
  },
  {
    id: 'fireball_run',
    name: 'Fireball',
    icon: '🔥',
    type: 'passive',
    description: 'Ball ignites on launch, doubling bumper score for 5 seconds.',
    effect: 'ignite_on_launch',
    value: 5,
  },
  {
    id: 'ice_trail_run',
    name: 'Ice Trail',
    icon: '❄️',
    type: 'passive',
    description: 'Ball leaves a frozen path; pegs in the trail give +50% bonus.',
    effect: 'ice_trail_run',
    value: 1.5,
  },
  {
    id: 'ball_split_run',
    name: 'Ball Split',
    icon: '⚡',
    type: 'active',
    description: 'Splits ball into 2 on next bumper hit (one use).',
    effect: 'ball_split_run',
    value: 1,
  },
  {
    id: 'lucky_portal_run',
    name: 'Lucky Portal',
    icon: '🌀',
    type: 'board',
    description: 'Adds a portal to the board this run.',
    effect: 'add_portal',
    value: 1,
  },
  {
    id: 'chain_explosion_run',
    name: 'Chain Explosion',
    icon: '💥',
    type: 'passive',
    description: 'Bumper hits at combo 5+ trigger nearby bumper chain.',
    effect: 'chain_explosion_run',
    value: 5,
  },
  {
    id: 'auto_multiplier_run',
    name: 'Auto Multiplier',
    icon: '✖️',
    type: 'passive',
    description: 'Slot multipliers increase by 1 every 8 seconds while ball is in play.',
    effect: 'auto_multiply_run',
    value: 8,
  },
  {
    id: 'extra_ball_run',
    name: 'Extra Ball',
    icon: '🎱',
    type: 'passive',
    description: 'Start this run with one additional ball.',
    effect: 'extra_ball',
    value: 1,
  },
  {
    id: 'gold_rush',
    name: 'Gold Rush',
    icon: '💰',
    type: 'passive',
    description: 'All gold rewards doubled for this run.',
    effect: 'gold_double',
    value: 2,
  },
];

/** Machine upgrades purchasable between stages */
export const MACHINE_UPGRADES = [
  {
    id: 'extra_bumper',
    name: 'Extra Bumper',
    icon: '🔵',
    type: UPGRADE_TYPE.BUMPER,
    description: 'Add a powerful bumper to your board. Bumpers score 3× normal peg value.',
    cost: 15,
    effect: 'add_bumper',
    maxCount: 5,
  },
  {
    id: 'portal_gate',
    name: 'Portal Gate',
    icon: '🌀',
    type: UPGRADE_TYPE.PORTAL,
    description: 'Add a portal pair. Balls entering a portal teleport to its partner.',
    cost: 20,
    effect: 'add_portal_pair',
    maxCount: 2,
  },
  {
    id: 'spinning_wheel',
    name: 'Spinning Wheel',
    icon: '⚙️',
    type: UPGRADE_TYPE.WHEEL,
    description: 'A rotating wheel that deflects balls unpredictably. Great for chaos builds.',
    cost: 18,
    effect: 'add_wheel',
    maxCount: 3,
  },
  {
    id: 'flipper_upgrade',
    name: 'Moving Flipper',
    icon: '🏏',
    type: UPGRADE_TYPE.FLIPPER,
    description: 'Add a flipper that activates when a ball passes near it.',
    cost: 25,
    effect: 'add_flipper',
    maxCount: 2,
  },
  {
    id: 'slot_multiplier',
    name: 'Slot Multiplier',
    icon: '✖️',
    type: UPGRADE_TYPE.MULTIPLIER,
    description: 'Upgrade a random slot to have a permanent 2× multiplier.',
    cost: 30,
    effect: 'upgrade_slot',
    maxCount: 4,
  },
  {
    id: 'split_path',
    name: 'Split Path',
    icon: '🔀',
    type: UPGRADE_TYPE.SPLIT,
    description: 'Adds a divider that creates two distinct paths through the board.',
    cost: 22,
    effect: 'add_split',
    maxCount: 2,
  },
  {
    id: 'extra_ball_slot',
    name: 'Extra Ball Lane',
    icon: '🎱',
    type: UPGRADE_TYPE.EXTRA_BALL,
    description: 'One losing slot becomes a recycle slot that returns the ball.',
    cost: 35,
    effect: 'recycle_slot',
    maxCount: 1,
  },
];

/** Permanent meta-progression unlocks */
export const PERMANENT_UNLOCKS = [
  {
    id: 'unlock_machine_volcano',
    name: 'Volcano Machine',
    icon: '🌋',
    description: 'Unlock the Volcano machine theme with lava physics.',
    cost: 50,
    type: 'machine',
  },
  {
    id: 'unlock_machine_space',
    name: 'Space Station',
    icon: '🚀',
    description: 'Unlock the Space Station theme with low-gravity physics.',
    cost: 80,
    type: 'machine',
  },
  {
    id: 'starting_slime',
    name: 'Start with Slime',
    icon: '🟢',
    description: 'Every new run begins with the Slime creature.',
    cost: 30,
    type: 'starting_creature',
  },
  {
    id: 'harder_mode',
    name: 'Challenge Mode',
    icon: '💀',
    description: 'Unlock a harder difficulty with better rewards.',
    cost: 100,
    type: 'difficulty',
  },
  {
    id: 'extra_starting_gold',
    name: 'Investor',
    icon: '💰',
    description: 'Start every run with 10 extra gold.',
    cost: 40,
    type: 'starting_bonus',
  },
];
